# Add your additional Hyprland configurations here
cursor {
    no_hardware_cursors = false
}

# Autostart
exec-once = hyprpm reload
exec-once = Telegram
exec-once = sunshine

# Plugins
plugin {
    hyprexpo {
        columns = 3
        gap_size = 20
        bg_col = rgb(111111)
        workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1

        #gesture_distance = 300 # how far is the "max" for the gesture
    }

    hyprbars {
        # example config
        bar_height = 20

        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(ff4040), 12, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(eeee11), 10, , hyprctl disp\atch fullscreen 1
    }
}


# Binds
unbind = ALT, TAB
unbind = ALT SHIFT, TAB
unbind = , XF86Tools
unbind = SHIFT SUPER, H
unbind = SUPER, g

bind = , XF86Tools, exec, spotify-launcher
bind = ALT, TAB, exec, rofi -show window -replace -i -window-format "{w} · {t}"
bind = ALT SHIFT, TAB, exec, rofi -show window -replace -i -window-format "{w} · {t}" -kb-accept-entry '!Alt-Tab'
bind = SUPER, g, hyprexpo:expo, toggle
bind = SHIFT SUPER, X, exec, systemctl poweroff
bind = SHIFT SUPER, H, exec, sh -c /home/simo/.mydotfiles/com.ml4w.dotfiles.stable/.config/waybar/scripts/ha_rofi_menu.sh 


# Windows rules
windowrule {
    name = no-hyprbars-on-tiled-windows
    hyprbars:no_bar = true
    match:float = 0
}

windowrule {
    name = hyprbars-on-terminal
    hyprbars:no_bar = false
    match:class = ^(kitty|org.kde.kate)$
}

windowrule {
  name = firefox-to-ws
  match:class = firefox
  workspace = 1
}

windowrule {
  name = nautilus-to-ws
  match:class = org.gnome.Nautilus
  workspace = 2
}

windowrule {
  name = code-to-ws
  match:class = code
  workspace = 3
}

windowrule {
  name = spt-to-ws
  match:class = spotify
  workspace = 4
}

windowrule {
  name = telegram-to-ws
  match:class = org.telegram.desktop
  workspace = 5 silent
}

windowrule {
  name = winboat-to-ws
  match:class = xfreerdp
  workspace = 8
}
